"""A file with a list of confidence boosters from which to choose randomly.
sources: 
    sepitajima.com/quotes-boost-confidence-courage-and-self-belief-tips/
    https://daringtolivefully.com/self-esteem-quotes
    https://www.codeofliving.com/life/quotes/27-powerful-quotes-to-boost-your-self-confidence/
    https://www.inc.com/jeff-haden/50-inspiring-motivational-quotes-to-increase-your-confidence.html
"""

BOOSTERS = [
    "Because one believes in oneself, one doesn’t try to convince others. Because one is content with oneself, one doesn’t need others’ approval. Because one accepts oneself, the whole world accepts him or her. ~ Lao Tzu",
    "Life is ten percent what you experience and ninety percent how you respond to it.  ~ Dorothy M. Neddermeyer",
    "Noble and great. Courageous and determined. Faithful and fearless. That is who you are and who you have always been. And understanding it can change your life, because this knowledge carries a confidence that cannot be duplicated any other way. ~ Sheri L. Dew",
    "Each time we face our fear, we gain strength, courage, and confidence in the doing. ~ Theodore Roosevelt",
    "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves. We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.  ~ Marie Curie",
    "One important key to success is self-confidence. An important key to self-confidence is preparation. ~ Arthur Ashe",
    "To love yourself right now, just as you are, is to give yourself heaven. Don’t wait until you die. If you wait, you die now. If you love, you live now.  ~ Alan Cohen",
    "Think like a queen. A queen if not afraid to fail. Failure is another stepping stone to greatness.  ~ Oprah",
    "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, Who am I to be brilliant, gorgeous, talented, fabulous? Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won’t feel insecure around you. We are all meant to shine, as children do. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others.  ~ Marianne Williamson",
    "You are the only person on earth who can use your ability.  ~ Zig Ziglar",
    "Have confidence that if you have done a little thing well, you can do a bigger thing well too.  ~ David Storey",
    "Don’t wait until everything is just right. It will never be perfect. There will always be challenges, obstacles and less than perfect conditions. So what. Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident and more and more successful.  ~ Mark Victor Hansen",
    "With realization of one’s own potential and self-confidence in one’s ability, one can build a better world.  ~ Dalai Lama",
    "Don’t you dare, for one more second, surround yourself with people who are not aware of the greatness that you are.  ~ Jo Blackwell-Preston",
    "Wouldn’t it be powerful if you fell in love with yourself so deeply that you would do just about anything if you knew it would make you happy? This is precisely how much life loves you and wants you to nurture yourself. The deeper you love yourself, the more the universe will affirm your worth. Then you can enjoy a lifelong love affair that brings you the richest fulfillment from inside out.  ~ Alan Cohen",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.  ~ Ralph Waldo Emerson",
    "Don’t live down to expectations. Go out there and do something remarkable.  ~ Wendy Wasserstein",
    "Self-confidence is the memory of success.  ~ David Storey",
    "No one can make you feel inferior without your consent.  ~ Eleanor Roosevelt",
    "We have to learn to be our own best friends because we fall too easily into the trap of being our own worst enemies.  ~ Roderick Thorp",
    "Whether you think you can or think you can’t, you are right.  ~ Henry Ford",
    "If you really put a small value upon yourself, rest assured that the world will not raise your price.  ~ Author Unknown",
    "You have to expect things of yourself before you can do them.  ~ Michael Jordan",
    "Confidence is preparation.  Everything else is beyond your control.  ~ Richard Kline",
    "The way to develop self-confidence is to do the thing you fear and get a record of successful experiences behind you. ~ William Jennings Bryan",
    "If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced. ~ Vincent Van Gogh",
    "Always be yourself and have faith in yourself. Do not go out and look for a successful personality and try to duplicate it. ~ Bruce Lee",
    "Don't wait until everything is just right. It will never be perfect. There will always be challenges, obstacles, and less than perfect conditions. So what? Get started now. With each step you take, you will grow stronger and stronger, more and more skilled, more and more self-confident, and more and more successful. ~ Mark Victor Hansen",
    "You wouldn't worry so much about what others think of you if you realized how seldom they do. ~ Eleanor Roosevelt",
    "Low self-confidence isn't a life sentence. Self-confidence can be learned, practiced, and mastered--just like any other skill. Once you master it, everything in your life will change for the better. ~ Barrie Davenport",
    "Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight, or any experience that reveals the human spirit. ~ e.e. cummings",
    "Trust yourself. Create the kind of self that you will be happy to live with all your life. Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement. ~ Golda Meir",
    "One important key to success is self-confidence. An important key to self-confidence is preparation. ~ Arthur Ashe",
    "It is confidence in our bodies, minds, and spirits that allows us to keep looking for new adventures. ~ Oprah Winfrey",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. ~ Ralph Waldo Emerson",
    "But failure has to be an option in art and in exploration--because it's a leap of faith. And no important endeavor that required innovation was done without risk. You have to be willing to take those risks ...  ~ James Cameron",
    "People are like stained-glass windows. They sparkle and shine when the sun is out, but when the darkness sets in their true beauty is revealed only if there is light from within. ~ Elisabeth Kubler-Ross",
    "Confidence comes not from always being right but from not fearing to be wrong. ~ Peter T. Mcintyre",
    "Argue for your limitations and, sure enough, they're yours. ~ Richard Bach",
    "The courage to be is the courage to accept oneself, in spite of being unacceptable. ~ Paul Tillich",
    "If we all did the things we are capable of doing, we would literally astound ourselves. ~ Thomas Alva Edison",
    "Shyness has a strange element of narcissism, a belief that how we look, how we perform, is truly important to other people.  ~ Andre Dubus",
    "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness, that most frightens us. We ask ourselves, 'Who am I to be brilliant, gorgeous, talented, fabulous?' Actually, who are you not to be? ~ Marianne Williamson",
    "Talk to yourself like you would to someone you love. ~ Brene Brown",
    "Trust yourself. You know more than you think you do. ~ Dr. Benjamin Spock",
    "Successful people have fear, successful people have doubts, and successful people have worries. They just don't let these feelings stop them. ~ T. Harv Eker",
    "You can have anything you want if you are willing to give up the belief that you can't have it. ~ Dr. Robert Anthony",
    "It is not the mountain we conquer, but ourselves. ~ Sir Edmund Hillary",
    "To love oneself is the beginning of a life-long romance. ~ Oscar Wilde",
    "I had to grow to love my body. I did not have a good self-image at first. Finally it occurred to me, I'm either going to love me or hate me. And I chose to love myself. Then everything kind of sprung from there. Things that I thought weren't attractive became sexy. Confidence makes you sexy. ~ Queen Latifah",
    "You yourself, as much as anyone in the entire universe deserve your love and affection. ~ Buddha",
    "Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy. ~ Dale Carnegie",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. ~ Helen Keller",
    "Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude. ~ Thomas Jefferson",
    "Confidence is a habit that can be developed by acting as if you already had the confidence you desire to have. ~ Brian Tracy",
    "When I started counting my blessings, my whole life turned around. ~ Willie Nelson",
    "If you are insecure, guess what? The rest of the world is, too. Do not overestimate the competition and underestimate yourself. You are better than you think. ~ T. Harv Eker",
    "Wouldn't it be powerful if you fell in love with yourself so deeply that you would do just about anything if you knew it would make you happy? This is precisely how much life loves you and wants you to nurture yourself. The deeper you love yourself, the more the universe will affirm your worth. Then you can enjoy a lifelong love affair that brings you the richest fulfillment from inside out. ~ Alan Cohen",
    "To anyone that ever told you you're no good ... They're no better. ~ Hayley Williams",
    "Always remember you are braver than you believe, stronger than you seem, and smarter than you think. ~ Christopher Robin",
    "You have no control over other people's taste, so focus on staying true to your own. ~ Tim Gunn",
    "No one can make you feel inferior without your consent. ~ Eleanor Roosevelt",
    "The moment you doubt whether you can fly, you cease forever to be able to do it. ~ J.M. Barrie",
    "It's a dead-end street if you sit around waiting for someone else to tell you you're okay. ~ Michael Pitt",
    "I think that the power is the principle. The principle of moving forward, as though you have the confidence to move forward, eventually gives you confidence when you look back and see what you've done. ~ Robert Downey, Jr.",
    "If you're presenting yourself with confidence, you can pull off pretty much anything. ~ Katy Perry",
    "Twenty years from now you will be more disappointed by the things you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sail. Explore. Dream. Discover. ~ Mark Twain",
    "I've finally stopped running away from myself. Who else is there better to be? ~ Goldie Hawn",
    "Don't be satisfied with stories, how things have gone with others. Unfold your own myth. ~ Rumi",
    "When you're different, sometimes you don't see the millions of people who accept you for what you are. All you notice is the person who doesn't. ~ Jodi Picoult",
    "As soon as you trust yourself, you will know how to live. ~ Johann Wolfgang von Goethe",
    "You cannot be lonely if you like the person you're alone with. ~ Wayne Dyer",
    "Don't waste your energy trying to change opinions ... do your thing, and don't care if they like it. ~ Tina Fey",
    "Pride is holding your head up when everyone around you has theirs bowed. Courage is what makes you do it. ~ Bryce Courtenay",
    "You yourself, as much as anybody in the entire universe, deserve your love and affection. ~  ~ Buddha",
    "Your chances of success in any undertaking can always be measured by your belief in yourself. ~  ~ Robert Collier",
    "The strongest single factor in prosperity consciousness is self-esteem: believing you can do it, believing you deserve it, believing you will get it. ~  Jerry Gillies",
    "There is overwhelming evidence that the higher the level of self-esteem, the more likely one will be to treat others with respect, kindness, and generosity. ~  Nathaniel Branden",
    "The golden opportunity you are seeking is in yourself. It is not in your environment, it is not in luck or chance, or the help of others; it is in yourself alone. ~  Orison Swett Marden",
    "Listen to your heart above all other voices. ~  Marta Kagan",
    "Always be a first-rate version of yourself, instead of a second-rate version of somebody else. ~  Judy Garland",
    "You were not born a winner, and you were not born a loser. You are what you make yourself be. ~  Lou Holtz",
    "Self-trust is the first secret of success. ~  Ralph Waldo Emerson",
    "The most important opinion you have is the one you have of yourself, and the most significant things you say all day are those things you say to yourself. ~  Unknown Author",
    "No one can make you feel inferior without your consent. ~  Eleanor Roosevelt",
    "Trust yourself. Create the kind of self that you will be happy to live with all your life. Make the most of yourself by fanning the tiny, inner sparks of possibility into flames of achievement. ~  Golda Meir",
    "Someone else’s opinion of you does not have to become your reality. ~  Les Brown",
    "I was always looking outside myself for strength and confidence but it comes from within. It is there all the time. ~  Anna Freud",
    "If I am not for myself, who will be? ~   Pirke Avoth",
    "The tragedy is that so many people look for self-confidence and self-respect everywhere except within themselves, and so they fail in their search. ~  Dr. Nathaniel Branden",
    "It took me a long time not to judge myself through someone else’s eyes. ~  Sally Field",
    "The way you treat yourself sets the standard for others. ~  Dr. Sonya Friedman",
    "There is only one corner of the universe you can be certain of improving, and that’s your own self. ~  Aldous Leonard Huxley",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. ~  Brian Tracy",
    "Aerodynamically the bumblebee shouldn’t be able to fly, but the bumblebee doesn’t know that so it goes on flying anyway. ~  Mary Kay Ash",
    "If you doubt you can accomplish something, then you can’t accomplish it. You have to have confidence in your ability, and then be tough enough to follow through. ~  Rosalyn Smith Carter",
    "Confidence comes not from always being right but from not fearing to be wrong. ~  Peter Mcintyre",
    "We have to learn to be our own best friends because we fall too easily into the trap of being our own worst enemies. ~  Roderick Thorp",
    "It ain’t what they call you, it’s what you answer to. ~  W.C. Fields",
    "Whether you think you can or think you can’t  ~ you are right. ~  Henry Ford",
    "I am convinced all of humanity is born with more gifts than we know. Most are born geniuses and just get de-geniused rapidly. ~  Buckminster Fuller",
    "If you really put a small value upon yourself, rest assured that the world will not raise your price. ~ Author Unknown",
    "Thousands of geniuses live and die undiscovered  ~ either by themselves or by others. ~  Mark Twain",
    "Nothing splendid has ever been achieved except by those who dared believe that something inside of them was superior to circumstance. ~  Bruce Barton",
    "Always act like you’re wearing an invisible crown. ~  Author Unknown",
    "What a man thinks of himself, that it is which determines, or rather indicates his fate. ~ Henry David Thoreau",
    "The best way to gain self-confidence is to do what you are afraid to do. ~  Author Unknown",
    "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, Who am I to be brilliant, gorgeous, talented, fabulous? Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won’t feel insecure around you. We are all meant to shine, as children do. We were born to make manifest the glory of God that is within us. It is not just in some of us; it is in everyone. And as we let our own light shine, we unconsciously give other people permission to do the same. As we are liberated from our own fear, our presence automatically liberates others. ~  Marianne Williamson",
    "Well, we all know that self-esteem comes from what you think of you, not what other people think of you. ~  ~ Gloria Gaynor",
    "To trust one’s mind and to know that one is worthy of happiness is the essence of self-esteem. ~  Nathaniel Branden",
    "Too many people overvalue what they are not, and undervalue what they are. ~  Malcolm Forbes",
    "Of all the judgments we pass in life, none is more important than the judgment we pass on ourselves ~  ~ Nathaniel Branden.",
    "One of the most significant characteristics of healthy esteem is that it is the state of one who is not at war either with himself or with others ~  ~ Nathaniel Branden.",
    "The most important key to the permanent enhancement of esteem is the practice of positive inner-talk ~  ~ Dennis Waitley.",
    "The greatest success is successful self-acceptance. ~  Ben Sweet",
    "Love is the great miracle cure. Loving ourselves works miracles in our lives. ~  Louise L. Hay.",
    "To have an incredible increase in self esteem, all you have to do is start doing some little something. You don’t have to do spectacularly dramatic things for self esteem to start going off the scale. Just make a commitment to any easy discipline. Then another one and another one. ~  Jim Rohn",
    "Self worth cannot be verified by others. You are worthy because you say it is so. If you depend on others for your value it is other-worth. ~  Wayne Dyer",
    "Persons of high self esteem are not driven to make themselves superior to others; they do not seek to prove their value by measuring themselves against a comparative standard. Their joy is being who they are, not in being better than someone else. ~  Nathaniel Branden",
    "Having a low opinion of yourself is not ‘modesty’. It’s self-destruction. Holding your uniqueness in high regard is not ‘egotism’. It’s a necessary precondition to happiness and success. ~  Bobbe Sommer",
    "Tell me how a person judges his or her self esteem and I will tell you how that person operates at work, in love, in sex, in parenting, in every important aspect of existence – and how high he or she is likely to rise. The reputation you have with yourself – your self-esteem – is the single most important factor for a fulfilling life. ~  Nathaniel Branden",
    "Never bend your head. Hold it high. Look the world straight in the eye. ~  Helen Keller",
    "Today you are you, that is truer than true. There is no one alive who is youer than you. ~  Dr. Seuss",
    "People are like stained-glass windows. They sparkle and shine when the sun is out, but when the darkness sets in their true beauty is revealed only if there is light from within. ~  Elisabeth Kübler-Ross",

]